language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git --recursive
  - cd ZendSkeletonApplication
  - cp ../DoctrineModule/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - rm -rf vendor/doctrine/DoctrineModule
  - cp -r ../DoctrineModule vendor/doctrine/
  - rm config/application.config.php && cp ../DoctrineModule/.travis/application.config.php config/

script:
  - ./vendor/bin/doctrine-module help
  - ./vendor/bin/doctrine-module list
